# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - CinemaAppAzure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install && mvn package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CREDENTIALS }}.client_id
          subscription_id: ${{ secrets.AZURE_CREDENTIALS }}.subscription_id
          tenant_id: ${{ secrets.AZURE_CREDENTIALS }}.tenant_id

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-spring-apps.outputs.spring-app-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Spring Apps production
        uses: azure/spring-apps-deploy@v1
        with:
          app-name: 'CinemaAppAzure'
          slot-name: 'Production'
          azure-subscription: d09cd68b-c52a-457a-ac99-595738d8e914
          service-name: asa-ls4bjeuhtpcma-standard
          use-staging-deployment: false
          package: '${{ github.workspace }}/**/*.jar'
